defaults: &defaults
  working_directory: /opt/iroha
  environment:
    IROHA_HOME: /opt/iroha
    IROHA_BUILD: /opt/iroha/build

version: 2

jobs:
  build:
    <<: *defaults
    docker:
      - image: hyperledger/iroha-docker-develop
      - image: postgres:9.5
      - image: redis:3.2.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-debug-{{ arch }}-{{ .Branch }}-
            - build-cache-debug-{{ arch }}-
          paths:
            - ~/.ccache
      - run:
          name: cmake
          command: >
            cmake \
              -DCOVERAGE=ON \
              -H$IROHA_HOME \
              -B$IROHA_BUILD \
              -DCMAKE_BUILD_TYPE=Debug
      - run:
          name: make
          command: |
            cmake --build $IROHA_BUILD -- -j4
      - save_cache:
          key: build-cache-debug-{{ arch }}-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.ccache
      - run: ccache --show-stats
      - run:
          name: unit tests, generate xunit-*.xml
          command: cmake --build $IROHA_BUILD --target test
      - run:
          name: coverage info
          command: cmake --build $IROHA_BUILD --target gcovr
      - run:
          name: cppcheck
          command: cmake --build $IROHA_BUILD --target cppcheck
      - persist_to_workspace:
          root: /opt/iroha/build
          paths:
            - compile_commands.json
            - reports



  build-linux-release:
    <<: *defaults
    docker:
      - image: hyperledger/iroha-docker-develop
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-release-{{ arch }}-{{ .Branch }}-
            - build-cache-release-{{ arch }}-
          paths:
            - ~/.ccache
      - run:
          name: cmake
          command: >
            cmake \
              -DCOVERAGE=OFF \
              -DTESTING=OFF \
              -H$IROHA_HOME \
              -B$IROHA_BUILD \
              -DCMAKE_BUILD_TYPE=Release \
              -DPACKAGE_DEB=ON \
              -DPACKAGE_TGZ=ON
      - run:
          name: make and package
          command: |
            cmake --build $IROHA_BUILD --target package -- -j4
      - save_cache:
          key: build-cache-release-{{ arch }}-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.ccache
      - run:
          name: copy deb file
          command: |
            cd $IROHA_BUILD
            cp *.deb ./iroha.deb
            cp *.tar.gz ./iroha.tar.gz
            # if IROHA_VERSION is not set, then CIRCLE_BUILD_NUM
            echo ${IROHA_VERSION:-$CIRCLE_BUILD_NUM} > version.txt
            cd $IROHA_HOME
      - run:
          name: copy dockerfile to build dir
          command: cp $IROHA_HOME/docker/release_dockerfile $IROHA_HOME/build/release_dockerfile.tmp
      - store_artifacts:
          path: build/iroha.deb
          destination: iroha-linux.deb
      - store_artifacts:
          path: build/iroha.tar.gz
          destination: iroha-linux.tar.gz
      - store_artifacts:
          path: build/version.txt
          destination: version.txt
      - persist_to_workspace:
          root: build
          paths:
            - iroha.deb
            - release_dockerfile.tmp



  dockerize:
    <<: *defaults
    docker:
      - image: hyperledger/iroha-docker-develop
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /opt/iroha/build
      - run:
          name: Copy deb
          command: |
            cp $IROHA_BUILD/iroha.deb $IROHA_HOME/docker/iroha.deb
      - run:
          name: Copy dockerfile
          command: cp $IROHA_HOME/build/release_dockerfile.tmp $IROHA_HOME/docker
      - run:
          name: Docker login
          command: |
              docker login -u $DOCKER_USER -p "$DOCKER_PASS"
      - run:
          name: Build and push iroha image
          command: |
              tag=test
              if [ "$CIRCLE_BRANCH" == "develop" ]; then
                tag=develop
              elif [ "$CIRCLE_BRANCH" == "master" ]; then
                tag=latest
              fi
              cd $IROHA_HOME/docker
              docker build -f release_dockerfile -t hyperledger/iroha-docker:$tag .
              docker push hyperledger/iroha-docker:$tag


  # used to push info about issues to github
  sonar-pr:
    <<: *defaults
    docker:
      - image: hyperledger/iroha-docker-develop
    steps:
      - checkout
      - restore_cache:
          keys:
            - sonar-
      - attach_workspace:
          at: /opt/iroha/build
      - run:
          name: codecov.io
          command: bash <(curl -s https://codecov.io/bash) -f $IROHA_BUILD/reports/gcovr.xml || echo "Codecov did not collect coverage reports"
      - run:
          name: execute sonar-scanner to analyze PR
          command: >
            if [ ! -z "$SONAR_TOKEN" ] && \
              [ ! -z "$SORABOT_TOKEN" ] && \
              [ ! -z "$CIRCLE_BUILD_NUM" ] && \
              [ ! -z "$CI_PULL_REQUEST" ]; then
              sonar-scanner \
                -Dsonar.github.disableInlineComments \
                -Dsonar.github.repository="hyperledger/iroha" \
                -Dsonar.analysis.mode=preview \
                -Dsonar.login=${SONAR_TOKEN} \
                -Dsonar.projectVersion="${CIRCLE_BUILD_NUM}" \
                -Dsonar.github.oauth="${SORABOT_TOKEN}" \
                -Dsonar.github.pullRequest="$(echo $CI_PULL_REQUEST | egrep -o "[0-9]+")"
            else
              echo "required env vars not found"
            fi
      - save_cache:
          key: sonar-{{ epoch }}
          paths:
            - ~/.sonar


  # executed only for develop, master and release branches
  sonar-release:
    <<: *defaults
    docker:
      - image: hyperledger/iroha-docker-develop
    steps:
      - checkout
      - restore_cache:
          keys:
            - sonar-
      - attach_workspace:
          at: /opt/iroha/build
      - run:
          name: codecov.io
          command: bash <(curl -s https://codecov.io/bash) -f $IROHA_BUILD/reports/gcovr.xml || echo "Codecov did not collect coverage reports"
      - run:
          name: execute sonar-scanner
          command: >
            if [ ! -z "$SONAR_TOKEN" ] && \
              [ ! -z "$CIRCLE_BUILD_NUM" ] && \
              [ ! -z "$CIRCLE_BRANCH" ]; then
              sonar-scanner \
                -Dsonar.login="${SONAR_TOKEN}" \
                -Dsonar.projectVersion="${CIRCLE_BUILD_NUM}" \
                -Dsonar.branch="${CIRCLE_BRANCH}"
            else
              echo "required env vars not found"
            fi
      - save_cache:
          key: sonar-{{ epoch }}
          paths:
            - ~/.sonar


  build-macos-release:
    macos:
      xcode: 9.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - brew-{{ arch }}
          paths:
            - Library/Caches/Homebrew
      - run:
          name: install dev dependencies
          command: brew install cmake boost postgres grpc autoconf automake libtool ccache
      - save_cache:
          key: brew-{{ arch }}-{{ epoch }}
          paths:
            - Library/Caches/Homebrew
      - restore_cache:
          keys:
            - build-cache-{{ arch }}-{{ .Branch }}
          paths:
            - ~/.ccache
      - restore_cache:
          keys:
            - external-{{ arch }}-{{ .Branch }}
            - external-{{ arch }}
          paths:
            - external
      - run: ccache --show-stats
      - run:
          name: cmake
          command: >
            cmake -H. -Bbuild \
              -DCOVERAGE=OFF \
              -DTESTING=OFF \
              -DPACKAGE_TGZ=ON \
              -DCMAKE_BUILD_TYPE=Release
      - run:
          name: make
          command: |
            cmake --build build --target package -- -j$(sysctl -n hw.ncpu)
      - save_cache:
          key: build-cache-{{ arch }}-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.ccache
      - save_cache:
          key: external-{{ arch }}-{{ .Branch }}-{{ epoch }}
          paths:
            - external
      - run: ccache --show-stats
      - run:
          name: rename artifacts
          command: |
            cp build/*.tar.gz build/iroha-darwin.tar.gz
            # if IROHA_VERSION is not set, then CIRCLE_BUILD_NUM
            echo ${IROHA_VERSION:-$CIRCLE_BUILD_NUM} > build/version.txt
      - store_artifacts:
          path: build/iroha-darwin.tar.gz
          destination: iroha-darwin.tar.gz
      - store_artifacts:
          path: build/version.txt
          destination: version.txt

     

workflows:
  version: 2
  full_pipeline:
    jobs:
      # build-macos-release + build -> sonar(pr/release)
      - build-macos-release
      - build
      - sonar-pr:
          requires:
            - build
          filters:
            branches:
              ignore:
                - develop
                - master
            tags:
              # do not invoke sonar-pr for tags
              ignore: /.*/
      # invoke sonar-release whenever anything to master, develop is pushed
      # or any commit tagged with v[\.0-9]+.*
      - sonar-release:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
            tags:
              only: /v[\.0-9]+.*/

      # build-linux-release -> dockerize
      - build-linux-release:
          filters:
            branches:
              only:
                - develop
                - master
            tags:
              only: /v[\.0-9]+.*/
      - dockerize:
          requires:
            - build-linux-release
          filters:
            branches:
              only:
                - develop
                - master
            tags:
              only: /v[\.0-9]+.*/
